# Cloud Build Configuration for Automatic Deployment
# Triggers on push to main branch

steps:
  # Step 1: Build the Docker image with no cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/game:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/game:latest'
      - '.'
    timeout: 600s

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/game:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/game:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'moes-casino'
      - '--image=gcr.io/$PROJECT_ID/game:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--cpu-boost'

# Automatically tag images
images:
  - 'gcr.io/$PROJECT_ID/game:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/game:latest'

# Build timeout
timeout: 1200s

# Options
# COST OPTIMIZATION: Default builder (e2-medium) uses 1x build minutes vs N1_HIGHCPU_8's 8x rate
# This preserves the 120 free build-minutes/day on Google Cloud Free Tier
options:
  # machineType: 'N1_HIGHCPU_8'  # DISABLED - burns free tier 8x faster
  logging: CLOUD_LOGGING_ONLY
